import openai
from config import OPENAI_API_KEY
from prompts import build_listing_prompt
 
# Create the OpenAI client — think of this as 'opening a connection'
# to OpenAI's servers. You do this once at the top.
client = openai.OpenAI(api_key=OPENAI_API_KEY)
 
 
def generate_listing(details: dict, language: str = "English") -> str:
    """
    Takes property details as a dictionary and returns a
    formatted listing string generated by GPT-4o.
    
    Args:
        details: dict with keys: type, location, area, price, amenities
        language: "English", "Hindi", or "Marathi"
    
    Returns:
        str: The generated property listing
    """
    
    # Build the prompt using our template
    prompt = build_listing_prompt(details, language)
    
    # try/except: if the API call fails (no internet, bad key, etc.)
    # we catch the error and show a helpful message instead of crashing
    try:
        response = client.chat.completions.create(
            model="gpt-4o",         # The AI model to use
            messages=[
                {
                    "role": "system",
                    "content": "You are a professional Indian real estate agent."
                },
                {
                    "role": "user", 
                    "content": prompt
                }
            ],
            max_tokens=800,         # Max length of response (~600 words)
            temperature=0.7,        # Creativity level: 0=robotic, 1=very creative
        )
        
        # Extract the text from the response object
        # response.choices[0].message.content is where the text lives
        return response.choices[0].message.content
        
    except openai.AuthenticationError:
        return "Error: Invalid API key. Check your .env file."
    except openai.RateLimitError:
        return "Error: API rate limit hit. Wait 60 seconds and try again."
    except Exception as e:
        return f"Unexpected error: {str(e)}"
 
 
def generate_listing_batch(properties: list, language: str = "English") -> list:
    """
    Generate listings for multiple properties at once.
    Returns a list of listing strings in the same order.
    """
    return [generate_listing(prop, language) for prop in properties]
