import openai
import base64
import logging
from config import OPENAI_API_KEY
from prompts import build_listing_prompt

# ── Logging setup ────────────────────────────────────────────
# Prints timestamped logs to terminal so you can see what is happening
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s"
)
logger = logging.getLogger(__name__)

# ── OpenAI client ────────────────────────────────────────────
# Created once at module level — reused for every API call
client = openai.OpenAI(api_key=OPENAI_API_KEY)


def generate_listing(details: dict, language: str = "English") -> str:
    """
    Takes property details as a dictionary and returns a formatted
    listing string generated by GPT-4o.

    Fixes applied vs original:
    - Added timeout=30 to prevent indefinite hanging
    - max_tokens is now language-aware (Hindi/Marathi need more tokens)
    - Added APITimeoutError handler
    - Added logging for every call and every error

    Args:
        details: dict with keys: type, location, area, price, amenities,
                 floor, facing, photo_description
        language: "English", "Hindi", or "Marathi"

    Returns:
        str: The generated property listing text
    """
    logger.info(f"Generating listing | location={details.get('location')} | lang={language}")

    prompt = build_listing_prompt(details, language)

    # Hindi and Marathi use more tokens per character (Devanagari script)
    # 1000 tokens is enough for English, 1500 for Indian languages
    max_tok = 1500 if language in ["Hindi", "Marathi"] else 1000

    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "system",
                    "content": "You are a professional Indian real estate agent."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            max_tokens=max_tok,
            temperature=0.7,
            timeout=30,  # raises APITimeoutError if OpenAI takes more than 30s
        )

        logger.info("Listing generated successfully")
        return response.choices[0].message.content

    except openai.AuthenticationError:
        logger.error("Authentication failed — API key is invalid")
        return "Error: Invalid API key. Check your .env file."

    except openai.RateLimitError:
        logger.warning("Rate limit hit")
        return "Error: API rate limit hit. Wait 60 seconds and try again."

    except openai.APITimeoutError:
        logger.warning("API call timed out after 30 seconds")
        return "Error: Request timed out. OpenAI servers are slow right now. Try again in 30 seconds."

    except Exception as e:
        logger.error(f"Unexpected error in generate_listing: {e}", exc_info=True)
        return f"Unexpected error: {str(e)}"


def describe_image(image_bytes: bytes, file_type: str = "image/jpeg") -> str:
    """
    Sends a property photo to GPT-4o Vision and returns a 2-3 sentence
    description that gets injected into the listing prompt.

    Fixes applied vs original:
    - file_type parameter added — correctly handles PNG vs JPEG
    - Added timeout=20
    - Added logging

    Args:
        image_bytes: raw bytes of the uploaded photo
        file_type: MIME type string e.g. "image/jpeg" or "image/png"
                   Pass photo.type from Streamlit's UploadedFile object

    Returns:
        str: visual description, or "" if it fails (listing still generates)
    """
    if not image_bytes:
        logger.warning("describe_image called with empty bytes — skipping")
        return ""

    logger.info(f"Describing image | type={file_type} | size={len(image_bytes)} bytes")

    # Convert image bytes to base64 string for the API
    image_b64 = base64.b64encode(image_bytes).decode("utf-8")

    # Use the correct MIME type — was hardcoded as jpeg before (Bug #7 fix)
    mime = file_type if file_type.startswith("image/") else "image/jpeg"

    try:
        response = client.chat.completions.create(
            model="gpt-4o",
            messages=[{
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": """Describe this property photo in 2-3 sentences for a real estate listing.
Focus on: room type, flooring material, lighting quality, key features or fixtures, and overall condition.
Be specific and factual. No exaggeration. Example style:
'Spacious living room with vitrified tile flooring and large east-facing windows
providing ample natural light. Features a false ceiling with recessed lighting and
a modular TV unit with storage.'"""
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": f"data:{mime};base64,{image_b64}"
                        }
                    }
                ]
            }],
            max_tokens=150,
            timeout=20,
        )

        description = response.choices[0].message.content
        logger.info("Image described successfully")
        return description

    except Exception as e:
        # If image description fails for any reason, return empty string
        # The listing will still generate — just without visual details
        logger.warning(f"Image description failed: {e}")
        return ""


def generate_listing_batch(properties: list, language: str = "English") -> list:
    """
    Generate listings for multiple properties with rate limit protection.

    Fixes applied vs original:
    - Added sleep between requests to prevent rate limit errors
    - Returns list of dicts with success/error status per item
      instead of raw strings (so caller can tell which ones failed)

    Args:
        properties: list of property detail dicts
        language: output language for all listings

    Returns:
        list of dicts: [{"success": True, "listing": "..."}, {"success": False, "error": "..."}]
    """
    import time

    results = []

    for i, prop in enumerate(properties):
        logger.info(f"Batch: generating {i+1} of {len(properties)}")
        listing = generate_listing(prop, language)

        if listing.startswith("Error:"):
            results.append({"success": False, "error": listing, "property": prop})
        else:
            results.append({"success": True, "listing": listing, "property": prop})

        # Wait between requests to avoid rate limits
        # Skip the wait after the last item
        if i < len(properties) - 1:
            logger.info("Batch: waiting 5 seconds before next request")
            time.sleep(5)

    return results